apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-catalogservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-catalogservice
  template:
    metadata:
      labels:
        app: my-catalogservice
    spec:
      containers:
        - name: my-catalogservice
          image: changwskr/my-catalogservice:1.0
          ports:
            - containerPort: 8080
